name: Build and Push Multiarch Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual trigger
  schedule: # Automatic monthly trigger
    - cron: '0 0 1 * *' # Runs at 0:00 the first day of each month

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCK_U }}
          password: ${{ secrets.DOCK_P }}

      - name: Build and Push Multiarch 087K/webvowl image embedding last official webvolw
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t 087K/webvowl:latest\
            --push .

