name: Build and Push Multiarch Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual trigger
  schedule: # Automatic monthly trigger
    - cron: '0 0 1 * *' # Runs at 0:00 the first day of each month

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCK_U }}
          password: ${{ secrets.DOCK_P }}

      - name: pull 087k/webvowl:v1.1.7 to keep repo alive and use it as cache
        run: |
         docker pull 087k/webvowl:v1.1.7

      - name: Build and Push Multiarch 087K/webvowl image embedding last official webvolw
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from type=registry,ref=087k/webvowl:v1.1.7 \
            -t 087k/webvowl:latest \
            --push .

